"""initial server schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-04 12:02:49.656369
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_telegram_users',
    sa.Column('telegram_id', sa.String(length=40), nullable=False),
    sa.Column('telegram_username', sa.String(length=80), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'viewer')", name='ck_telegram_role'),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('os_type', sa.String(length=20), nullable=True),
    sa.Column('os_info', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_fingerprint_hash'), 'devices', ['fingerprint_hash'], unique=True)
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_pending', 'notification_outbox', ['sent_at', 'created_at'], unique=False)
    op.create_table('activation_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('app_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_telegram_id', sa.String(length=40), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_device_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("app_type IN ('matrix_generator', 'remote_hp')", name='ck_key_app_type'),
    sa.CheckConstraint("status IN ('pending', 'consumed', 'expired', 'cancelled')", name='ck_key_status'),
    sa.ForeignKeyConstraint(['consumed_by_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_keys_code'), 'activation_keys', ['code'], unique=True)
    op.create_index(op.f('ix_activation_keys_status'), 'activation_keys', ['status'], unique=False)
    op.create_table('activity_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('app_type', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('client_report_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint("app_type IN ('matrix_generator', 'remote_hp')", name='ck_report_app_type'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'client_report_id', name='uq_device_report_id')
    )
    op.create_index('idx_reports_app_type_event', 'activity_reports', ['app_type', 'event_type'], unique=False)
    op.create_index('idx_reports_device_time', 'activity_reports', ['device_id', 'occurred_at'], unique=False)
    op.create_table('app_authorizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('app_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token_prefix', sa.String(length=24), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('session_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_ip', sa.String(length=64), nullable=True),
    sa.CheckConstraint("app_type IN ('matrix_generator', 'remote_hp')", name='ck_auth_app_type'),
    sa.CheckConstraint("status IN ('active', 'revoked')", name='ck_auth_status'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'app_type', name='uq_device_app')
    )
    op.create_index(op.f('ix_app_authorizations_device_id'), 'app_authorizations', ['device_id'], unique=False)
    op.create_index(op.f('ix_app_authorizations_session_id'), 'app_authorizations', ['session_id'], unique=False)
    op.create_index(op.f('ix_app_authorizations_token_prefix'), 'app_authorizations', ['token_prefix'], unique=True)
    op.create_table('heartbeats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('app_type', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_heartbeat_device_app_time', 'heartbeats', ['device_id', 'app_type', 'received_at'], unique=False)
    op.create_table('suspicion_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('app_type', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('existing_session_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_request_ip', sa.String(length=64), nullable=True),
    sa.Column('admin_reviewed', sa.Boolean(), nullable=False),
    sa.Column('admin_action', sa.String(length=16), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("admin_action IS NULL OR admin_action IN ('ignored', 'revoked')", name='ck_suspicion_action'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suspicion_device_time', 'suspicion_events', ['device_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_suspicion_events_admin_reviewed'), 'suspicion_events', ['admin_reviewed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suspicion_events_admin_reviewed'), table_name='suspicion_events')
    op.drop_index('idx_suspicion_device_time', table_name='suspicion_events')
    op.drop_table('suspicion_events')
    op.drop_index('idx_heartbeat_device_app_time', table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_index(op.f('ix_app_authorizations_token_prefix'), table_name='app_authorizations')
    op.drop_index(op.f('ix_app_authorizations_session_id'), table_name='app_authorizations')
    op.drop_index(op.f('ix_app_authorizations_device_id'), table_name='app_authorizations')
    op.drop_table('app_authorizations')
    op.drop_index('idx_reports_device_time', table_name='activity_reports')
    op.drop_index('idx_reports_app_type_event', table_name='activity_reports')
    op.drop_table('activity_reports')
    op.drop_index(op.f('ix_activation_keys_status'), table_name='activation_keys')
    op.drop_index(op.f('ix_activation_keys_code'), table_name='activation_keys')
    op.drop_table('activation_keys')
    op.drop_index('idx_outbox_pending', table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_devices_fingerprint_hash'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('admin_telegram_users')
    # ### end Alembic commands ###
